apiVersion: v1
kind: Service
metadata:
  name: {{ include "stress.fullname" . }}
  labels:
    {{- include "stress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stress.selectorLabels" . | nindent 4 }}
