# Default values for outline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

config:
  # -- Whether or not to create the secret to hold the config
  createSecret: true
  # -- The name of the secret that contains the env for configuration.
  # only used if config.createSecret is false
  secretName: you-created-it
  # -- Additional environment variable keypairs for configuration
  env:
    DEFAULT_LANGUAGE: Y2FjaGUscHJlc2VudGVycyxldmVudHMsZW1haWxzLG1haWxlcix1dGlscyxtdWx0aXBsYXllcixzZXJ2ZXIsc2VydmljZXM=
    DEBUG: Y2FjaGUscHJlc2VudGVycyxldmVudHMsZW1haWxzLG1haWxlcix1dGlscyxtdWx0aXBsYXllcixzZXJ2ZXIsc2VydmljZXM=
  # -- Should point to the fully qualified, publicly accessible URL.
  url: 'http://localhost:3000'
  # -- Internal port to serve on
  port: '3000'
  # -- URL of postgres db. Used if built-in postgres is disabled and createSecret is true
  databaseURL: ""
  # -- URL of postgres test db. Used if built-in postgres is disabled and createSecret is true
  databaseURLTest: ""
  # -- URL of redis. Used if built-in redis is disabled and createSecret is true
  redisURL: ""
  # -- Generate a unique random key, you can use `openssl rand -hex 32` in terminal
  secretKey: 9430cad3bc716024794a4085b538d6312692a97ef3459a94709245f55ffb163e
  # -- Generate a unique random key, you can use `openssl rand -hex 32` in terminal
  utilsSecret: f96ac69ead8567b7f2fe3e87015327f76735e3830b9f1d40d782ec68ff544d65
  slack:
    enabled: false
    key: ""
    secret: ""
    verificationToken: ""
    appID: ""
    messageActions: "true"
  googleAuth:
    enabled: false
    clientID: ""
    clientSecret: ""
    allowedDomains: ""

postgresql:
  enabled: true
  # -- The admin password for built-in postgres. Username is postgres
  postgresqlPassword: 59c05b0be92b6095b1d33ab398a54c6987add725fd7d8b0ced5ffccd2c9929a2
  postgresqlDatabase: outline
redis:
  enabled: true
  usePassword: false
minio:
  enabled: true
  defaultBuckets: "outline"

image:
  repository: outlinewiki/outline
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
