apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse.fullname" . }}-config
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
stringData:
  log.config: |-
    version: 1
    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    filters:
      context:
        (): synapse.logging.context.LoggingContextFilter
        request: ""
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
        filters: [context]
    loggers:
      synapse.storage.SQL:
        # beware: increasing this to DEBUG will make synapse log sensitive
        # information such as access tokens.
        level: INFO
    root:
      level: INFO
      handlers: [console]
    disable_existing_loggers: false
  homeserver.yaml: |-
    ## Server ##
    server_name: "{{ .Values.serverName }}"
    pid_file: /homeserver.pid
    web_client: False
    soft_file_limit: 0
    log_config: "/config/log.config"
    ## Ports ##
    listeners:
    - port: 8008
      tls: false
      bind_addresses: ['::']
      type: http
      x_forwarded: false
      resources:
      - names: [client]
        compress: true
      - names: [federation]
        compress: false
    ## Database ##
    database:
      {{- if .Values.postgres.enabled }}
      name: "psycopg2"
      args:
        user: {{ .Values.postgres.user }}
        password: {{ .Values.postgres.password }}
        database: {{ .Values.postgres.database }}
        {{- if .Values.postgres.localDev.enabled }}
        host: {{ include "synapse.fullname" . }}-dev-postgres
        port: 5432
        {{- else }}
        host: {{ .Values.postgres.host }}
        port: {{ .Values.postgres.port }}
        {{- end }}
        cp_min: {{ .Values.postgres.cpMin }}
        cp_max: {{ .Values.postgres.cpMax }}
      {{- else }}
      name: "sqlite3"
      args:
        database: "/data/homeserver.db"
      {{- end }}
    ## Performance ##
    event_cache_size: "10K"
    ## Ratelimiting ##
    rc_messages_per_second: 0.2
    rc_message_burst_count: 10.0
    federation_rc_window_size: 1000
    federation_rc_sleep_limit: 10
    federation_rc_sleep_delay: 500
    federation_rc_reject_limit: 50
    federation_rc_concurrent: 3
    ## Files ##
    media_store_path: "/data/media"
    uploads_path: "/data/uploads"
    max_upload_size: "10M"
    max_image_pixels: "32M"
    dynamic_thumbnails: false
    # List of thumbnail to precalculate when an image is uploaded.
    thumbnail_sizes:
    - width: 32
      height: 32
      method: crop
    - width: 96
      height: 96
      method: crop
    - width: 320
      height: 240
      method: scale
    - width: 640
      height: 480
      method: scale
    - width: 800
      height: 600
      method: scale
    url_preview_enabled: False
    max_spider_size: "10M"
    ## Captcha ##
    recaptcha_public_key: "YOUR_PUBLIC_KEY"
    recaptcha_private_key: "YOUR_PRIVATE_KEY"
    enable_registration_captcha: False
    recaptcha_siteverify_api: "https://www.google.com/recaptcha/api/siteverify"
    ## Turn ##
    turn_uris: []
    turn_shared_secret: "YOUR_SHARED_SECRET"
    turn_user_lifetime: "1h"
    turn_allow_guests: True
    ## Registration ##
    enable_registration: {{ .Values.enableRegistration }}
    registration_shared_secret: {{ .Values.regSharedSecret | quote }}
    bcrypt_rounds: 12
    allow_guest_access: False
    enable_group_creation: true
    # The list of identity servers trusted to verify third party
    # identifiers by this server.
    #
    # Also defines the ID server which will be called when an account is
    # deactivated (one will be picked arbitrarily).
    trusted_third_party_id_servers:
    - matrix.org
    - vector.im
    ## Metrics ###
    enable_metrics: False
    report_stats: False
    ## API Configuration ##
    room_invite_state_types:
    - "m.room.join_rules"
    - "m.room.canonical_alias"
    - "m.room.avatar"
    - "m.room.name"
    app_service_config_files: []
    macaroon_secret_key: {{ .Values.macaroonSecretKey | quote }}
    expire_access_token: False
    ## Signing Keys ##
    signing_key_path: "/secrets/signing.key"
    old_signing_keys: {}
    key_refresh_interval: "1d" # 1 Day.
    suppress_key_server_warning: True
    # The trusted servers to download signing keys from.
    perspectives:
      servers:
        "matrix.org":
          verify_keys:
            "ed25519:auto":
              key: "Noi6WqcDj0QmPxCNQqgezwTlBKrfqehY1u2FyWP9uYw"
    password_config:
      enabled: true
