{{- if .Values.config.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: opaque
data:
  {{- toYaml .Values.config.env | nindent 2 }}
  SECRET_KEY: {{ .Values.config.secretKey | b64enc }}
  UTILS_SECRET: {{ .Values.config.utilsSecret | b64enc }}
  URL: {{ .Values.config.url | b64enc }}
  PORT: {{ .Values.config.port | b64enc }}
  DATABASE_URL: {{ include "postgresql.url" . | b64enc }}
  DATABASE_URL_TEST: {{ include "postgresql.urlTest" . | b64enc }}
  REDIS_URL: {{ include "redis.url" . | b64enc }}

  {{- if .Values.config.slack.enabled }}
  SLACK_KEY: {{ .Values.config.slack.key | b64enc }}
  SLACK_SECRET: {{ .Values.config.slack.secret | b64enc }}
  SLACK_VERIFICATION_TOKEN: {{ .Values.config.slack.verificationToken | b64enc }}
  SLACK_APP_ID: {{ .Values.config.slack.appID | b64enc }}
  SLACK_MESSAGE_ACTIONS: {{ .Values.config.slack.messageActions | b64enc }}
  {{- end }}

  {{- if .Values.config.googleAuth.enabled }}
  GOOGLE_CLIENT_ID: {{ .Values.config.googleAuth.clientID | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.config.googleAuth.clientSecret | b64enc }}
  {{- if .Values.config.googleauth.allowedDomains | b64enc }}
  ALLOWED_DOMAINS: {{ .Values.config.googleAuth.allowedDomains | b64enc }}
  {{- end }}
  {{- end }}
  FORCE_HTTPS: ZmFsc2UgLW4K
  ENABLE_UPDATES: ZmFsc2UgLW4K
  {{- if .Values.minio.enabled }}
  AWS_ACCESS_KEY_ID: 'get_a_key_from_aws'
  AWS_SECRET_ACCESS_KEY: 'get_the_secret_of_above_key'
  AWS_REGION: 'xx-xxxx-x'
  AWS_S3_UPLOAD_BUCKET_URL: 'http://s3:4569'
  AWS_S3_UPLOAD_BUCKET_NAME: 'bucket_name_here'
  AWS_S3_UPLOAD_MAX_SIZE: '26214400'
  AWS_S3_FORCE_PATH_STYLE: true
  AWS_S3_ACL: 'private'
  {{- end }}
{{- end }}
