{{- if .Values.config.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: opaque
stringData:
  {{- toYaml .Values.config.env | nindent 2 }}
{{- end }}
