{{- if .Values.config.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: opaque
stringData:
  {{- toYaml .Values.config.env | nindent 2 }}
  SECRET_KEY: {{ .Values.config.secretKey | quote }}
  UTILS_SECRET: {{ .Values.config.utilsSecret | quote }}
  URL: {{ .Values.config.url | quote }}
  PORT: {{ .Values.config.port | quote }}

  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: "TODO url for built-in postgres"
  DATABASE_URL_TEST: 'postgres://user:pass@localhost:5532/outline-test'
  {{- else }}
  DATABASE_URL: {{ .Values.config.databaseURL | quote }}
  DATABASE_URL_TEST: {{ .Values.config.databaseURLTest | quote }}
  {{- end }}

  {{- if .Values.redis.enabled }}
  REDIS_URL: 'TODO url for built-in redis'
  {{- else }}
  REDIS_URL: {{ .Values.config.redisURL | quote }}
  {{- end }}

  {{- if .Values.config.slack.enabled }}
  SLACK_KEY: {{ .Values.config.slack.key }}
  SLACK_SECRET: {{ .Values.config.slack.secret }}
  SLACK_VERIFICATION_TOKEN: {{ .Values.config.slack.verificationToken }}
  SLACK_APP_ID: {{ .Values.config.slack.appID }}
  SLACK_MESSAGE_ACTIONS: {{ .Values.config.slack.messageActions }}
  {{- end }}

  {{- if .Values.config.googleAuth.enabled }}
  GOOGLE_CLIENT_ID: {{ .Values.config.googleAuth.clientID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.config.googleAuth.clientSecret | quote }}
  {{- if .Values.config.googleauth.allowedDomains }}
  ALLOWED_DOMAINS: {{ .Values.config.googleAuth.allowedDomains | quote }}
  {{- end }}
  {{- end }}

  FORCE_HTTPS: false
  ENABLE_UPDATES: false
  DEBUG: 'cache,presenters,events,emails,mailer,utils,multiplayer,server,services'

  {{- if .Values.minio.enabled }}
  AWS_ACCESS_KEY_ID: 'get_a_key_from_aws'
  AWS_SECRET_ACCESS_KEY: 'get_the_secret_of_above_key'
  AWS_REGION: 'xx-xxxx-x'
  AWS_S3_UPLOAD_BUCKET_URL: 'http://s3:4569'
  AWS_S3_UPLOAD_BUCKET_NAME: 'bucket_name_here'
  AWS_S3_UPLOAD_MAX_SIZE: '26214400'
  AWS_S3_FORCE_PATH_STYLE: true
  AWS_S3_ACL: 'private'
  {{- end }}
{{- end }}
