{{- if not .Values.config.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nocodb.fullname" . }}-config
  labels:
    {{- include "nocodb.labels" . | nindent 4 }}
data:
  {{- if .Values.config.dbConnectionString }}
  NC_DB: {{ .Values.config.dbConnectionString | b64enc }}
  {{- else }}
  NC_DB_JSON: {{ .Values.config.dbConnectionJSON | b64enc }}
  {{- end }}
  {{- range $k, $v := .Values.config.additionalConfig }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
